
- name: Extract files
  become: true
  unarchive: 
    src: files/artifact.tar.gz
    dest: /home/ubuntu

- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu
    npm install
    pm2 stop default
    sudo pm2 start npm -- start