#cleanup:
    #docker:
     # - image: amazon/aws-cli
    #steps:
     # - checkout
      #- run:
       #   name: Remove old stacks and files
        #  command: |
            # Fetch the old stack workflow id
         #   export OldWorkflowID=$(aws cloudformation \
          #    list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
           #   --no-paginate --output text)
            #echo Old Workflow ID: $OldWorkflowID

            # Fetch the stack names
            #export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
            #--stack-status-filter CREATE_COMPLETE --no-paginate --output text))
            #echo "Stack names are ${STACKS[@]}"
            
            # Condition to remove stacks/s3 bucket
            #if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
            #then
             # echo "Removing stacks/s3 bucket"
              # Remove stacks
              #aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
              #aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
              #aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"  
          #fi  


       #- cleanup:
          #requires: [cloudfront-update]    